name = "tg-networking-nhatrang"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "networking_nhatrang"
database_id = "da3337f2-02ad-49ef-b577-09916aa08763"

[[kv_namespaces]]
binding = "CACHE"
id = "aed391de129a4490a3d390731bd9ae90"

[triggers]
crons = ["0 0 * * *"]

[vars]
MINI_APP_URL = "https://spaguet.github.io/networking_nhatrang/"
